# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NmapScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_text', models.CharField(max_length=1024)),
                ('cmd_text', models.CharField(max_length=256)),
                ('start_date', models.DateTimeField(verbose_name='date started')),
                ('end_date', models.DateTimeField(verbose_name='date end')),
            ],
        ),
    ]
