# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmapscan',
            name='email_text',
            field=models.CharField(default='websecweb@gmail.com', max_length=64),
            preserve_default=False,
        ),
    ]
