# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmaper', '0002_nmapscan_email_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='NmapProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args_text', models.CharField(max_length=1024)),
                ('pub_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
