# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nmaper', '0005_nmapprofile_profilename_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nmapprofile',
            old_name='profilename_text',
            new_name='alias_text',
        ),
    ]
