# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmaper', '0006_auto_20160108_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmapscan',
            name='slug_text',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
