# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmaper', '0007_nmapscan_slug_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nmapscan',
            name='slug_text',
        ),
        migrations.AddField(
            model_name='nmapscan',
            name='slug',
            field=models.SlugField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
