# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmaper', '0010_auto_20160108_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nmapscan',
            name='email_text',
            field=models.EmailField(max_length=32),
        ),
    ]
